# report_generator.py - Professional report generation
from datetime import datetime
import os
from config import Config

class ReportGenerator:
    def __init__(self, filename):
        self.filename = os.path.join(Config.REPORTS_DIR, filename)
        self.content = []
    
    def add_header(self):
        self.content.append("="*80)
        self.content.append(f"{Config.WORKSHOP_NAME:^80}")
        self.content.append("="*80)
        self.content.append(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self.content.append(f"Report ID: {datetime.now().strftime('%Y%m%d%H%M%S')}")
        self.content.append(f"Generated by: Bless Digital Diagnostic System v2.0")
        self.content.append("="*80)
        self.content.append("")
    
    def add_vehicle_info(self, vehicle_info):
        self.content.append("VEHICLE INFORMATION")
        self.content.append("-"*80)
        self.content.append(f"Customer:     {vehicle_info.get('customer', 'Walk-in Customer')}")
        self.content.append(f"Make/Model:   {vehicle_info.get('make', 'N/A')} {vehicle_info.get('model', 'N/A')}")
        self.content.append(f"Year:         {vehicle_info.get('year', 'N/A')}")
        self.content.append(f"VIN:          {vehicle_info.get('vin', 'N/A')}")
        self.content.append(f"License:      {vehicle_info.get('license_plate', 'N/A')}")
        self.content.append(f"Mileage:      {vehicle_info.get('mileage', 'N/A')} km")
        self.content.append("")
    
    def add_diagnostic_results(self, diagnosis):
        self.content.append("DIAGNOSTIC RESULTS")
        self.content.append("-"*80)
        
        # Severity
        severity_icons = {'low': '🟢', 'medium': '🟡', 'high': '🔴', 'critical': '💀'}
        icon = severity_icons.get(diagnosis.get('severity', 'low'), '🟢')
        self.content.append(f"Severity:     {icon} {diagnosis.get('severity', 'low').upper()}")
        self.content.append("")
        
        # Symptoms
        self.content.append("SYMPTOMS REPORTED:")
        for symptom in diagnosis.get('symptoms', []):
            self.content.append(f"  • {symptom}")
        self.content.append("")
        
        # Analysis
        self.content.append("ANALYSIS & FINDINGS:")
        self.content.append(f"  {diagnosis.get('results', 'No issues found')}")
        self.content.append("")
        
        # Tools required
        if diagnosis.get('tools'):
            self.content.append("TOOLS REQUIRED:")
            for tool in diagnosis.get('tools', []):
                self.content.append(f"  • {tool}")
            self.content.append("")
        
        # Action plan
        self.content.append("REPAIR ACTION PLAN:")
        for step in diagnosis.get('action_plan', []):
            self.content.append(f"  {step}")
        self.content.append("")
    
    def add_cost_estimate(self, cost_estimate):
        self.content.append("COST ESTIMATE")
        self.content.append("-"*80)
        self.content.append(f"Labor Hours:  {cost_estimate.get('labor_hours', 0)} hours")
        self.content.append(f"Labor Rate:   ${Config.HOURLY_RATE:.2f}/hour")
        self.content.append(f"Labor Cost:   ${cost_estimate.get('labor_cost', 0):.2f}")
        self.content.append(f"Parts Cost:   ${cost_estimate.get('parts_cost', 0):.2f}")
        self.content.append(f"Subtotal:     ${cost_estimate.get('subtotal', 0):.2f}")
        self.content.append(f"Tax ({Config.TAX_RATE*100:.0f}%):    ${cost_estimate.get('tax', 0):.2f}")
        self.content.append("="*80)
        self.content.append(f"TOTAL:        ${cost_estimate.get('total', 0):.2f}")
        self.content.append("")
    
    def add_technician_notes(self, notes):
        if notes:
            self.content.append("TECHNICIAN NOTES")
            self.content.append("-"*80)
            self.content.append(notes)
            self.content.append("")
    
    def add_footer(self):
        self.content.append("")
        self.content.append("="*80)
        self.content.append("IMPORTANT NOTES:")
        self.content.append("• This estimate is valid for 30 days")
        self.content.append("• Parts prices subject to change based on availability")
        self.content.append("• Additional issues may be found during repair")
        self.content.append("• Customer approval required before proceeding with repairs")
        self.content.append("")
        self.content.append("="*80)
        self.content.append(f"Thank you for choosing {Config.WORKSHOP_NAME}!")
        self.content.append("For questions, please call our service department.")
        self.content.append("="*80)
    
    def generate(self, vehicle_info, diagnosis, cost_estimate, technician_notes=""):
        # Calculate full cost estimate
        full_estimate = {
            'labor_hours': cost_estimate['labor_hours'],
            'labor_cost': cost_estimate['labor_hours'] * Config.HOURLY_RATE,
            'parts_cost': cost_estimate['parts_cost'],
            'subtotal': (cost_estimate['labor_hours'] * Config.HOURLY_RATE) + cost_estimate['parts_cost'],
            'tax': ((cost_estimate['labor_hours'] * Config.HOURLY_RATE) + cost_estimate['parts_cost']) * Config.TAX_RATE,
            'total': ((cost_estimate['labor_hours'] * Config.HOURLY_RATE) + cost_estimate['parts_cost']) * (1 + Config.TAX_RATE)
        }
        
        self.add_header()
        self.add_vehicle_info(vehicle_info)
        self.add_diagnostic_results(diagnosis)
        self.add_cost_estimate(full_estimate)
        self.add_technician_notes(technician_notes)
        self.add_footer()
        
        # Save to file
        with open(self.filename, 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.content))
        
        return self.filename
    
    def print_report(self):
        """Print report to console"""
        print('\n'.join(self.content))
